### ISSUE TITLE
Rich progressbar doesn't move for fast downloads

### ISSUE THREAD

**Issue by Koncopd** [laminlabs/bionty-base#167]
Downloaded successfully, but the progress bar is at zero.
![image](https://user-images.githubusercontent.com/3065736/213874791-55893912-6754-4dcf-b756-a0dc5237c68d.png)

**Comment by Zethson** [comment]
This is usually only an issue if the download is too fast :)

We can increase the updates per second. I'll look into it...

**Comment by Zethson** [comment]
![image](https://user-images.githubusercontent.com/21954664/215332621-ed95973f-0b96-40d9-910c-370a80426e78.png)
Works for me so I think this is the issue - your connection is too good :)
