### ISSUE TITLE
Ensure that all ontologies are reachable

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#175]
Define a CI job that polls all URLs `in versions.yaml`. Should run once a week or so and email on failure.

**Comment by sunnyosun** [comment]
This would be awesome! Could it also send an email about new versions that come out?

**Comment by Zethson** [comment]
Think that checking for new versions would be more work since not all ontologies host on the same website with some API to query for new versions.

I'll add the CI job this week. I already wrote similar code in the past and it should be quick.
