### ISSUE TITLE
Move lnbfx.lookup to bionty

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#180]
@Zethson let's discuss what to use for bfx pipelines, or do we even need it?

**Comment by Zethson** [comment]
I'm in favor of merging other lookups into bionty so that bionty becomes the universal lookup tool (grossly simplified).

Could you add a few more details, here outlining what needs to be done?

**Comment by sunnyosun** [comment]
We had a bfx pipeline lookup, which was similarly set up as the bionty ones, but here: https://github.com/laminlabs/lnbfx/blob/main/lnbfx/_lookup.py

We could have `BfxPipeline` as an entity in bionty, and essentially migrate that over.

Another thing is the vocabulary is currently hosted https://lamindb-test.s3.amazonaws.com/pipelines.json, manually curated by Bernardo from nf-core. We should switch to an auto download like the ontologies if possible. Do you know if there's a place to get a list of public pipelines?

**Comment by Zethson** [comment]
For nf-core pipelines there's https://nf-co.re/pipelines
It's generated using https://github.com/nf-core/nf-co.re/blob/master/update_pipeline_details.php which uses the Github API fetch stuff.

I'm not aware of any website/source that collects all recent pipelines from ALL sources (aka ones that are not nf-core)

**Comment by Zethson** [comment]
Yeah, I'd be in favor of moving it to here. I'll assign myself and will tackle this next week or so

**Comment by sunnyosun** [comment]
Thank you! Let's start with the nf-core + cellranger ones? which should be fine for our customers at least.
