### ISSUE TITLE
guide/index not found in EntityTable for docstring in Python 3.10+

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#184]
`/home/zeth/PycharmProjects/bionty/.nox/build-3-10/lib/python3.10/site-packages/bionty/_table.py:docstring of bionty._table.EntityTable:1: WARNING: unknown document: 'guide/index'`

@sunnyosun I can reproduce it. See discussion on the other PR.

**Comment by sunnyosun** [comment]
Interesting, and seems to be the case for py3.10, not py3.9 which the docs are built in CI. Thanks for spotting it, let's keep an eye!

**Comment by sunnyosun** [comment]
This reference is removed!
