### ISSUE TITLE
Storage path of yaml files

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#203]
IIRC they're currently stored in the path where the package is installed. Usually people don't fiddle with things there and the path is too complex. Should we store the yaml files in the home directories?

**Comment by sunnyosun** [comment]
Agreed! Let's move them to the root. 👍

**Comment by Zethson** [comment]
As outlined in the associated PR, I'd only actually move the `_local.yaml` and keep all others where they are, because they're actually pretty well hidden ^_^
