### ISSUE TITLE
Get rid of explicit filenames

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#221]
Think that we can even autogenerate the filenames dict and just look for stuff:

```
FILENAMES = {
    "human_hp": "phenotype_lookup.parquet",
}
```

shouldn't be necessary. This would kill the final thing to define in any Entity.

**Comment by sunnyosun** [comment]
Perfect! We can generate 1-1 correspondence to the .owl file.

**Comment by Zethson** [comment]
https://github.com/laminlabs/bionty/issues/191 could be related. Might need to add the species to the versions.yaml to find the right parquet file.
