### ISSUE TITLE
Automatically infer version for passed database

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#233]
We currently require both database and version to be passed explicitly if the default is not used. The associated version for the passed database is currently being looked up in the `_current.yaml`.

If only the database is passed we should attempt to fetch the latest version of this ontology and just use it. A warning wouldn't hurt.

**Comment by sunnyosun** [comment]
Was just about to report this! 😄 

<img width="1006" alt="Screenshot 2023-03-07 at 12 51 50" src="https://user-images.githubusercontent.com/38218185/223323907-817a8d59-7e87-47c6-aa07-e6854bcaaa9c.png">
