### ISSUE TITLE
Why do we store `orig_index` if `curate` is append-only and the index maintains integrity?

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/bionty-base#242]
What am I missing?
<img width="629" alt="image" src="https://user-images.githubusercontent.com/16916678/223782490-59bb5507-f478-40ae-80e2-caea108cd180.png">

**Comment by falexwolf** [comment]
@sunnyosun explains that `orig_index` is only needed for entities that have alternative names.

Only then, `.curate()` is a destructive operation.

In all other cases, `.curate()` merely appends the `__curated__` flag to indicate whether a column matches a reference.

**Comment by falexwolf** [comment]
The `case_sensitive` flag seems to modify the `orig_index`. Should have a unit test!

<img width="817" alt="image" src="https://user-images.githubusercontent.com/16916678/224032442-4e6cbcb9-ec14-4ffd-970f-f6c70cfb248d.png">

**Comment by sunnyosun** [comment]
The `case_sensitivity` is fixed: https://github.com/laminlabs/bionty/pull/255
