### ISSUE TITLE
Why is the reference field a class arg and not an arg of `curate()`?

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/bionty-base#243]
I'm fine the current design, but I think it'd feel more natural if `id` was an arg of `curate` and had a more explicit name.

However, I understand that if several class behaviors are affected (not just curate), any `CellType` instance should have that `id` field customized.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/16916678/223784809-ae05cc65-c5f1-43bb-8b81-46bfce299f0c.png">

**Comment by falexwolf** [comment]
Maybe it'd make sense to show in this minimal example what other functionality of `CellType` is affected by setting `id="name"` at intit!

**Comment by sunnyosun** [comment]
I added a session here this weekend but just saw your issue now: https://lamin.ai/docs/bionty/guide/lookup#instantiate-with-a-different-identifier

But maybe it benefits with an example that shows nothing will be curated if the id doesn't match the column identifier.

@Zethson Could you extend https://lamin.ai/docs/bionty/guide/curate#curating-genes to explain what happens with `Gene(id='symbol').curate(df_orig)`?

Perhaps it would also be good to move it somewhere more obvious?

Maybe on the landing page, we could already explain the out-of-the-box functions offered by inheriting `Entity` (might rename to `Bionty`, see [suggestion](https://laminlabs.slack.com/archives/C04M3R0DM3Q/p1678766814181499)? `.df`, `.lookup`, `.curate` and setting `id=`.

**Comment by Zethson** [comment]
I'm on it.

@sunnyosun WDYT about offering the `id` parameter (can be renamed because it's not that pretty as @falexwolf outlined and also confused me initially) also in `curate`?

=> Use the `id` as defined in the Entity by default (ensures pretty `df` printing) but just overwrite it if passed in `curate` which is more natural than changing it in the Entity object.

**Comment by sunnyosun** [comment]
Yes, sounds good to me! Thank you!
