### ISSUE TITLE
Database in lamindb doesn't seem to be recognized

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#247]
Here the Lamin instance is using `cl`, but the API still uses `ca`.
<img width="1019" alt="Screenshot 2023-03-10 at 20 43 21" src="https://user-images.githubusercontent.com/38218185/224319331-d235578d-ddb8-49fa-b507-4eb3861a8532.png">

**Comment by sunnyosun** [comment]
Also, why isn't `cl` the default even outside of lamindb, I thought the first one in the yaml is used?

<img width="779" alt="Screenshot 2023-03-10 at 20 44 51" src="https://user-images.githubusercontent.com/38218185/224319411-88b4f6ee-7e06-4a0a-a3e1-510bd2ab0b3a.png">

**Comment by Zethson** [comment]
Looks like they're ordered alphabetically in the `local.yaml`?

```
  14   │   ca:
  15   │     name: Human Cell Atlas Ontology
  16   │     versions:
  17   │       2022-12-16: https://www.ebi.ac.uk/ols/ontologies/hcao/download
  18   │     website: https://github.com/HumanCellAtlas/ontology
  19   │   cl:
  20   │     name: Cell Ontology
  21   │     versions:
  22   │       2022-08-16: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
  23   │       2023-02-15: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
  24   │     website: https://obophenotype.github.io/cell-ontology/
```

**Comment by Zethson** [comment]
```
def create_local(overwrite: bool = True) -> None:
    """If _local.yaml doesn't exist, copy from versions.yaml and create it.

    Args:
        overwrite: Whether to overwrite the current _local.yaml .
    """
    if not _LOCAL_PATH.exists() or overwrite:
        versions = load_yaml(VERSIONS_PATH)

        write_yaml(versions, _LOCAL_PATH)
```

This is pretty simple though... I'll need to learn where the alphabetical order is coming from

**Comment by Zethson** [comment]
pyyaml dumps things alphabetically by default :face_exhaling: 

```
sort_keys=False
```

**Comment by sunnyosun** [comment]
Got it! Thank you for spotting it so quickly!

But why does it create a lamindb instance with the `cl`?

**Comment by Zethson** [comment]
Maybe it's using an old `_current.yaml`? What's the content of it?

**Comment by Zethson** [comment]
@sunnyosun please reopen if the issue persists and we need to dig deeper!
