### ISSUE TITLE
Update local.yaml after timestamp check

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#259]
@Zethson this change https://github.com/laminlabs/bionty/pull/249 requires the `local.yaml` to be updated to contain the hashes, which is currently not done automatically.

Could you add a timestamp check for the existing `local.yaml` at the import time? If the file is created earlier than the PR merge time, add the hashes to the existing `local.yaml`? (Be aware that the `local.yaml` might already contain the custom dbs)

It's not a bit issue to just create a new `local.yaml` now since not many people are using bionty's new extension feature. But it would be great if we have a process that updates local.yaml if the format changes without breaking user's existing entries.

**Comment by Zethson** [comment]
Been playing around with some stuff and writing a few draft. I think that we need to versionize the versions.yml for a more generic solution.

We could always do incremental updates, but especially when users have very old versions of bionty with potentially very different yaml structures it's not so easy to update them and we would recommend to regenerate the local.yml. Think that this case is easier to detect with versionized yamls.

Then we also don't have to always compare time stamps but can simply compare yaml versions.

**Comment by sunnyosun** [comment]
Fully agreed! Shall we just write a line that contains version in the versions.yaml file?

**Comment by Zethson** [comment]
Yeah, but I'm also setting up code to migrate then. I'll hopefully ping you later with a draft :) A bit busy today.
