### ISSUE TITLE
Automatically upload latest ontologies to Lamin S3

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#270]
# Issue

We want to automate the process of uploading the latest ontologies to our S3 to solve the flakiness problem. 

# Proposed solution

Our solution is to leverage Lamin to upload the assets that are generated through CI runs like it's been done here: https://github.com/laminlabs/laminci/blob/1878b62ac1f9252ff4a14cf746c5772d8978d6a6/laminci/_artifacts.py#L8-L39

1. We would need to ensure that we're generating assets for ALL databases. While the notebooks currently don't cover all databases or even ontologies, the tests do (and should).
2. We only want to implement the data ingestion process but not the data retrieval process. Hence, lamindb shouldn't be a dependency of Bionty.
3. The process should be started on "push" events to "main".

# Implementation

1. Ensure that we're generating all required assets through the tests.
2. Find a way to learn which new assets have been added in a PR. A diff of versions or so. 
3. Prepare the assets for upload -> https://github.com/laminlabs/lamin-docs/blob/151623556b024063dac8305e3d5fb26dd6cd07c7/noxfile.py#L59-L125
4. Write a script to upload these to S3 -> https://github.com/laminlabs/laminci/blob/1878b62ac1f9252ff4a14cf746c5772d8978d6a6/laminci/_artifacts.py#L8-L39
5. Retrieve the URLs for the S3 artifacts and feed them back into the `versions.yml`.

Loop back the implementation experience to the lamindb crew.

**Comment by falexwolf** [comment]
Agreed on proposed solution!

> 2. Find a way to learn which new assets have been added in a PR. A diff of versions or so.

Why not just relying on the hash functionality of lamindb, which will by default error if you're trying to create a record for a storage object with the same hash?

> 3. Prepare the assets for upload -> https://github.com/laminlabs/lamin-docs/blob/151623556b024063dac8305e3d5fb26dd6cd07c7/noxfile.py#L59-L125

I don't think you need any of these for uploading!

Everything else seems great!

**Comment by falexwolf** [comment]
> 5. Retrieve the URLs for the S3 artifacts and feed them back into the versions.yml.

This should be something along the lines of 
```
s3path = dobject.load()
yaml_file.write(f"s3path={s3path}")
```
