### ISSUE TITLE
`update_defaults` not working

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#272]
<img width="959" alt="Screenshot 2023-03-22 at 13 21 42" src="https://user-images.githubusercontent.com/38218185/226809417-f76d53ac-5d9e-4d39-9790-bdf82ca63739.png">

Could we also add test of this function?

**Comment by Zethson** [comment]
Simple fix. IDK how this happened

`ROOT = Path(__file__).parent / "versions"` should be in `_sync_versions.py`
