### ISSUE TITLE
Consistent version style

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#294]
It's annoying to have to deal with versions like `7.7.4`. These can mess up paths and other stuff. It'd be easier if they were all `7-7-4` etc. Can edit a few, but also need to fix the bionty-assets

**Comment by sunnyosun** [comment]
What about adding a `version.replace('.', '_')` for the filename when saving the file?

Just need to covert back when loading the file, and hopefully there isn't usually _ in the versions.

**Comment by sunnyosun** [comment]
I wasn't aware it messes up the paths, but I had to convert them to strings when writing to `local.yaml`, `._current.yaml` and `._lndb.yaml`, otherwise pydantic will complain in lamindb.

From the user side, it would be better to be consistent with the source I think.

**Comment by Zethson** [comment]
Yeah, I had that yesterday, but it was inconsistent with the naming of the parquet files I think and then just annoying.
