### ISSUE TITLE
Rename curate to map

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#311]
- [x] Implement map for Iterables
- [x] Implement map for DataFrames
- [x] Implement inplace parameter for DataFrames
- [x] Deprecate `curate`
- [x] Update tests to use map

**Comment by sunnyosun** [comment]
I think `map` would be a different function that takes a list of identifiers and returns a mapped dict. While `curate` is an inplace function that takes a df and returns a df indexed with curated ids.

**Comment by falexwolf** [comment]
This sounds great!
