### ISSUE TITLE
Review the necessity of `species` parameter for each entity

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#320]

**Comment by Zethson** [comment]
Yeah, it should be optional. We can make it a kwarg only? Or handle it with None like we did for some other things (always feels a bit weird)

**Comment by Zethson** [comment]
I'm also a bit unhappy about the current design of "species" since this parameter is also database dependent and it's not always obvious which database is available for which species...

**Comment by sunnyosun** [comment]
Right, this should only be necessary for databases that contain multiple species, such as Ensembl, Uniprot, CellMarker.

Probably handling it with None is better for now, and for multi-species db, defaults to human?

**Comment by Zethson** [comment]
Closing in favor of https://github.com/laminlabs/bionty/issues/343
