### ISSUE TITLE
Display versions table without truncation

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#322]
I noticed the columns are truncated and it's hard for me to copy a version I want. @Zethson Could we display it without truncation? Or maybe just simply return a dataframe?

<img width="857" alt="Screenshot 2023-04-26 at 23 51 33" src="https://user-images.githubusercontent.com/38218185/234631533-91360baa-e0f6-44dd-90f2-c556aa68b250.png">

**Comment by Zethson** [comment]
Rich tables automatically fit the terminal width. The is the same behavior that e.g. Pandas DataFrames have. Nevertheless, I added an option to return a Pandas DataFrame.
