### ISSUE TITLE
Tissue doesn't by default use the latest uberon version

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#323]
It uses "2022-08-19" instead of "2023-02-14", despite both are present in the versions.yaml

<img width="312" alt="Screenshot 2023-04-26 at 23 58 58" src="https://user-images.githubusercontent.com/38218185/234633446-cf25a8b0-24c7-4dc2-945f-cf321bf84553.png">

**Comment by sunnyosun** [comment]
Same for the disease:

<img width="246" alt="Screenshot 2023-04-27 at 00 09 02" src="https://user-images.githubusercontent.com/38218185/234635957-39eb1601-d4df-4e10-bcd3-e62a07e77cd9.png">

**Comment by Zethson** [comment]
Could you please check your _current.yml and _lndb.yml ?

**Comment by Zethson** [comment]
If this is a new installation the defaults aren't set properly. I'll take a look then

**Comment by sunnyosun** [comment]
Ohhh! I init a new instance and was expecting the versions are set to be the most recent. But it was using the `.current,yml`. OK, never mind!
