### ISSUE TITLE
Pathway df doesn't have any names?

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#324]
<img width="270" alt="Screenshot 2023-04-27 at 00 23 52" src="https://user-images.githubusercontent.com/38218185/234640175-939fe7f9-9876-4138-b3ba-560a9270f5d5.png">

**Comment by Zethson** [comment]
Yeah, for some reason the obo files or any other ontology files do not provide the names? https://bioportal.bioontology.org/ontologies/PW/?p=summary

Maybe it's a parsing issue from pronto? The csv tables have them. Should I write a custom parser for the csv files and we use it ?!?

**Comment by sunnyosun** [comment]
Are you able to read using pronto? I got this error:

<img width="987" alt="Screenshot 2023-04-27 at 00 57 12" src="https://user-images.githubusercontent.com/38218185/234648504-2027e5a4-7b82-475c-b120-f4110d11dd2b.png">

**Comment by sunnyosun** [comment]
Oh I see, it only has names for `PW:xxxxxx` terms, we should use the prefix to filter for PW here.

<img width="394" alt="Screenshot 2023-04-27 at 01 02 57" src="https://user-images.githubusercontent.com/38218185/234649660-b41a3a76-23ce-4862-8d6c-d806d9d45526.png">

**Comment by sunnyosun** [comment]
And could we add GO(https://bioportal.bioontology.org/ontologies/GO) separately to include the `GO:xxxxxx` terms?

**Comment by Zethson** [comment]
WDYM with "separately" here? As its own ontology?

**Comment by sunnyosun** [comment]
Right! database="go"

**Comment by Zethson** [comment]
Fixed with https://github.com/laminlabs/bionty/pull/329

Creating a new issue for GO
