### ISSUE TITLE
Do we need both lndb & lndb-storage as dependencies?

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#334]
I thought we are just using UPath from lndb-storage, right? Could we remove lndb as a dependency?

**Comment by falexwolf** [comment]
UPath is in lndb meanwhile!

We can think about putting it somewhere else in the future!

**Comment by falexwolf** [comment]
We can remove lndb-storage!

**Comment by Zethson** [comment]
https://github.com/laminlabs/bionty/pull/335

Not quite :) I am afraid that we're lacking `fsspec` if we're removing lndb-storage. (Can be added as its own dependency but why is this not in lndb)? https://github.com/laminlabs/lndb/blob/main/pyproject.toml#L10
