### ISSUE TITLE
Human Cell Atlas Ontology

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#373]
I'm not sure if this should be in `CellType`, based on information here [Human Cell Atlas.](https://github.com/HumanCellAtlas/ontology), this includes Tissue, Cell Type, Anatomy and a bunch of other terms.

**Comment by Zethson** [comment]
This is actually an issue for several ontologies. We can add the ontologies to several Bionty entities and use our prefix filtering to always fetch the appropriate parts?

This will be quite some work for all the ones that we have but is probably the only good solution. WDYT?

**Comment by sunnyosun** [comment]
Yes, I agree! And I just specified prefixes for all ontologies in this PR (https://github.com/laminlabs/bionty/pull/372) to only include itself, which also cleaned up the parquet files a lot. Like "cl" only has terms start with `CL:`, as all other terms are just linked ontologies but not itself.

Then I was left with this problem only for Human Cell Atlas Ontology, because there's no dedicated prefix for it, it seems merely a collection of several ontologies.

**Comment by Zethson** [comment]
Ohhh, that's a great PR! I should have done that when I implemented the stuff oooff.

I'll do the HCAO then!
