### ISSUE TITLE
“Update version URLs” to run only when an actual upload is expected

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#389]
Now the “Update version URLs” CI fails because lamindb is no longer installed: https://github.com/laminlabs/bionty/actions/runs/5143134391/jobs/9257774303

But I don’t feel good about add “pip install lamindb” to the CI just for this because it takes long time, and this file uploading essentially occurs very infrequently upon push.

@Zethson Is there a way you can add a check so that lamindb is only installed when an actual upload is expected? Such as running a diff of the versions.yaml during after pushing to main?

**Comment by Zethson** [comment]
Idea:

```
import sys
import os

def file_has_changed(filename):
    try:
        file_modified_time = os.path.getmtime(filename)
    except FileNotFoundError:
        return True

    commit_files = os.popen('git diff --name-only HEAD~1').read().splitlines()

    return filename in commit_files


if __name__ == '__main__':
    target_file = 'path/to/your/file.ext'

    if file_has_changed(target_file):
        print(f'The file {target_file} has changed. Running the script...')
    else:
        print(f'The file {target_file} has not changed. Skipping script execution.')
```

**Comment by Zethson** [comment]
https://github.com/laminlabs/bionty/commit/eaa94e371ed89dbb8b705895447c5bb4cb95f097

Disabled it for now
