### ISSUE TITLE
LaminDB instance warning triggered in standalone mode

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#412]
![image](https://github.com/laminlabs/bionty/assets/21954664/7bf297ab-ff8e-420a-9754-a2795fd5907e)

Currently playing around with Bionty to finally write up vignettes for ehrapy and pertpy. The warning should not have been triggered should it? If yes, it is misleading and I don't get it.

**Comment by Zethson** [comment]
My `disease_bionty` also returns

`invalid Bionty object`

**Comment by sunnyosun** [comment]
You are right, thank you for testing it out! it's currently triggered as long as the source is passed inside an instance. I'll fix it!

**Comment by Zethson** [comment]
What do you think about raising an exception in this case? I was just left with a broken object which is not transparent or useful at all.

**Comment by sunnyosun** [comment]
Sorry, this should be fixed in the linked PR now. Nothing should be raised unless users passed a source that is not the currently_used source in lamindb.
