### ISSUE TITLE
Standalone misses lamindb_current_sources.yaml

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#418]
`FileNotFoundError: [Errno 2] No such file or directory: '/home/zeth/miniconda3/envs/ehrapy/lib/python3.10/site-packages/bionty/sources/.lamindb_current_sources.yaml'`

After upgrading to the latest version in a new environment and attempting to create a Disease object.

standalone mode

**Comment by Zethson** [comment]
(I can also have a look tomorrow)

**Comment by sunnyosun** [comment]
This is the intended behavior, this file is only generated if one init or loads an instance. Standalone bionty doesn't need this file.

I'm guessing what you have there is that you still have a local instance running. Could you try running "lamin close" with the most recent lamindb-setup?

**Comment by Zethson** [comment]
Ohhhhh indeed! I still had one running... I forgot about it :)
