### ISSUE TITLE
Improve docs headers

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#420]
![image](https://github.com/laminlabs/bionty/assets/21954664/593fe349-4ba4-4428-933a-9333767aa383)

Let's remove the examples after "Look up records of BLA" and "Access ontologies BLA". This does not scale.

**Comment by falexwolf** [comment]
I still think it gives users a concrete idea of which entities the guide is about - you could add a "etc." if this is meant to scale?

After all there is a bit of a difference between gene, protein, cellmarker and the "classical" ontologies, right?

**Comment by Zethson** [comment]
Yeah, that also works. But I'm not sure whether this would be all that pretty to be honest. These titles are pretty long then.
