### ISSUE TITLE
prefix filtering broken?

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#421]
![image](https://github.com/laminlabs/bionty/assets/21954664/1da7bc94-eb0b-40a9-9153-f7ab674892d3)

Due to recent changes? Thought it should only show MONDO now? @sunnyosun

**Comment by sunnyosun** [comment]
You probably have an old cached version in your /_dynamic, could you try emptying it?

**Comment by Zethson** [comment]
Deleted my whole /_dynamic and the problem persists

**Comment by sunnyosun** [comment]
Hmm, let me check! Perhaps just the S3 parquet file was not fixed before.

**Comment by sunnyosun** [comment]
Oh yeah, it was indeed broken, but not from this time because the parquet files were updated 2 weeks ago (I reuploaded everything back then), so the filtering was broken for at least two weeks now
