### ISSUE TITLE
Prettify inspect output

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#423]
![image](https://github.com/laminlabs/bionty/assets/21954664/f449b3a3-9ca8-4fe3-acba-a59381ca91c2)

We're just returning the dict now. Functional and useful, but doesn't look pretty. I also don't see the output visually scale all thaaaat much.

I need to brainstorm about this first.

**Comment by sunnyosun** [comment]
Try with "return_df=True"?

**Comment by Zethson** [comment]
Ya sure, that works (I even implemented it, heh? :) ) But it's not the default and I wonder whether it should be the other way around? :thinking:

**Comment by sunnyosun** [comment]
Just think returning dataframe is more canonical if user was working on a dataframe already, otherwise I think returning mapped vs unmapped lists are more intuitive for passing an iterable to an inspect function, no?

**Comment by Zethson** [comment]
Yeah, I agree.

**Comment by Zethson** [comment]
Discussed at length with @sunnyosun and we could not come up with something that is much easier and prettier. Closing for now.
