### ISSUE TITLE
✅ New records found in the public sources.yaml, updated /home/zeth/.lamin/bionty/versions/sources.local.yaml!

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#432]
Every time I import Bionty. Might be confusing for new users.

**Comment by sunnyosun** [comment]
Hmm, it doesn't log that for me, and based on the code, it should only logs when there's an update in the public source.yaml:https://github.com/laminlabs/bionty/blob/main/bionty/dev/_handle_sources.py#L162-L169

Could you try to print `additional_records` from the above function, and see why it's doing it every time?

**Comment by Zethson** [comment]
> [{'entity': 'Species', 'source': 'ensembl', 'species': 'all', 'version': 'release-108', 'url': 'https://ftp.ensembl.org/pub/release-108/species_EnsemblVertebrates.txt', 'md5': '', 'source_name': 'Ensembl', 'source_website': 'https://www.ensembl.org/index.html'}, {'entity': 'Gene', 'source': 'ensembl', 'species': 'human', 'version': 'release-108', 'url': 'https://ftp.ensembl.org/pub/release-108/mysql/homo_sapiens_core_108_38/', 'md5': '', 'source_name': 'Ensembl', 'source_website': 'https://www.ensembl.org/index.html'}, {'entity': 'Gene', 'source': 'ensembl', 'species': 'human', 'version': 'release-107', 'url': 'https://ftp.ensembl.org/pub/release-107/mysql/homo_sapiens_core_107_38/', 'md5': '', 'source_name': 'Ensembl', 'source_website': 'https://www.ensembl.org/index.html'}, {'entity': 'Gene', 'source': 'ensembl', 'species': 'mouse', 'version': 'release-108', 'url': 'https://ftp.ensembl.org/pub/release-108/mysql/mus_musculus_core_108_39/', 'md5': '', 'source_name': 'Ensembl', 'source_website': 'https://www.ensembl.org/index.html'}, {'entity': 'Protein', 'source': 'uniprot', 'species': 'human', 'version': '2022-04', 'url': 'https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/', 'md5': '', 'source_name': 'Uniprot', 'source_website': 'https://www.uniprot.org/'}, {'entity': 'Protein', 'source': 'uniprot', 'species': 'human', 'version': '2022-03', 'url': 'https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_03/', 'md5': '', 'source_name': 'Uniprot', 'source_website': 'https://www.uniprot.org/'}, {'entity': 'Protein', 'source': 'uniprot', 'species': 'mouse', 'version': '2022-04', 'url': 'https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/', 'md5': '', 'source_name': 'Uniprot', 'source_website': 'https://www.uniprot.org/'}, {'entity': 'CellMarker', 'source': 'cellmarker', 'species': 'human', 'version': '2.0', 'url': 'http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx', 'md5': '', 'source_name': 'CellMarker', 'source_website': 'http://bio-bigdata.hrbmu.edu.cn/CellMarker/'}, {'entity': 'CellMarker', 'source': 'cellmarker', 'species': 'mouse', 'version': '2.0', 'url': 'http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx', 'md5': '', 'source_name': 'CellMarker', 'source_website': 'http://bio-bigdata.hrbmu.edu.cn/CellMarker/'}, {'entity': 'CellLine', 'source': 'clo', 'species': 'all', 'version': '2022-03-21', 'url': 'https://data.bioontology.org/ontologies/CLO/submissions/65/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb', 'md5': 'ea58a1010b7e745702a8397a526b3a33', 'source_name': 'Cell Line Ontology', 'source_website': 'https://bioportal.bioontology.org/ontologies/CLO'}, {'entity': 'CellType', 'source': 'cl', 'species': 'all', 'version': '2023-02-15', 'url': 'http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl', 'md5': '9331a6a029cb1863bd0584ab41508df7', 'source_name': 'Cell Ontology', 'source_website': 'https://obophenotype.github.io/cell-ontology/'}, {'entity': 'CellType', 'source': 'cl', 'species': 'all', 'version': '2022-08-16', 'url': 'http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl', 'md5': 'd0655766574e63f3fe5ed56d3c030880', 'source_name': 'Cell Ontology', 'source_website': 'https://obophenotype.github.io/cell-ontology/'}, {'entity': 'Tissue', 'source': 'uberon', 'species': 'all', 'version': '2023-02-14', 'url': 'http://purl.obolibrary.org/obo/uberon/releases/2023-02-14/uberon.owl', 'md5': '3f94e22fae4cdde88a555c5cd59c47da', 'source_name': 'Uberon multi-species anatomy ontology', 'source_website': 'http://obophenotype.github.io/uberon/'}, {'entity': 'Tissue', 'source': 'uberon', 'species': 'all', 'version': '2022-08-19', 'url': 'http://purl.obolibrary.org/obo/uberon/releases/2022-08-19/uberon.owl', 'md5': 'c7c958a1ee48fdce146f2c1763eed27e', 'source_name': 'Uberon multi-species anatomy ontology', 'source_website': 'http://obophenotype.github.io/uberon/'}, {'entity': 'Disease', 'source': 'mondo', 'species': 'all', 'version': '2023-02-06', 'url': 'http://purl.obolibrary.org/obo/mondo/releases/2023-02-06/mondo.owl', 'md5': '2b7d479d4bd02a94eab47d1c9e64c5db', 'source_name': 'Mondo Disease Ontology', 'source_website': 'https://mondo.monarchinitiative.org/'}, {'entity': 'Disease', 'source': 'mondo', 'species': 'all', 'version': '2022-10-11', 'url': 'http://purl.obolibrary.org/obo/mondo/releases/2022-10-11/mondo.owl', 'md5': '04b808d05c2c2e81430b20a0e87552bb', 'source_name': 'Mondo Disease Ontology', 'source_website': 'https://mondo.monarchinitiative.org/'}, {'entity': 'Disease', 'source': 'doid', 'species': 'human', 'version': '2023-01-30', 'url': 'http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo', 'md5': '9f0c92ad2896dda82195e9226a06dc36', 'source_name': 'Human Disease Ontology', 'source_website': 'https://disease-ontology.org/'}, {'entity': 'Readout', 'source': 'efo', 'species': 'all', 'version': '3.48.0', 'url': 'http://www.ebi.ac.uk/efo/releases/v3.48.0/efo.owl', 'md5': '3367e9a9ae3dee9113024e5108c49091', 'source_name': 'The Experimental Factor Ontology', 'source_website': 'https://bioportal.bioontology.org/ontologies/EFO'}, {'entity': 'Phenotype', 'source': 'hp', 'species': 'human', 'version': '2023-01-27', 'url': 'https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-01-27/hp.owl', 'md5': 'ceeb3ada771908deef620d74cd8e6b0f', 'source_name': 'Human Phenotype Ontology', 'source_website': 'https://hpo.jax.org/'}, {'entity': 'Pathway', 'source': 'go', 'species': 'all', 'version': '2023-05-10', 'url': 'https://data.bioontology.org/ontologies/GO/submissions/1814/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb', 'md5': '', 'source_name': 'Gene Ontology', 'source_website': 'http://geneontology.org/docs/download-ontology/'}, {'entity': 'Pathway', 'source': 'pw', 'species': 'all', 'version': '7.79', 'url': 'https://data.bioontology.org/ontologies/PW/submissions/109/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb', 'md5': '02e2337bb1ab7cc4332ef6acc4cbdfa6', 'source_name': 'Pathway Ontology', 'source_website': 'https://www.ebi.ac.uk/ols/ontologies/pw'}, {'entity': 'BFXPipeline', 'source': 'lamin', 'species': 'all', 'version': '1.0.0', 'url': 's3://bionty-assets/bfxpipelines.json', 'md5': '', 'source_name': 'Bioinformatics Pipeline', 'source_website': 'https://lamin.ai'}, {'entity': 'Drug', 'source': 'dron', 'species': 'all', 'version': '2023-03-10', 'url': 'https://data.bioontology.org/ontologies/DRON/submissions/17/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb', 'md5': '', 'source_name': 'Drug Ontology', 'source_website': 'https://bioportal.bioontology.org/ontologies/DRON/?p=summary'}]

is the output

**Comment by Zethson** [comment]
source.local.yaml

> 
> version: 0.2.0
> Species:
>   ensembl:
>     all:
>       release-108:
>         source: https://ftp.ensembl.org/pub/release-108/species_EnsemblVertebrates.txt
>         md5: ''
>     name: Ensembl
>     website: https://www.ensembl.org/index.html
> Gene:
>   ensembl:
>     human:
>       release-108:
>         source: https://ftp.ensembl.org/pub/release-108/mysql/homo_sapiens_core_108_38/
>         md5: ''
>       release-107:
>         source: https://ftp.ensembl.org/pub/release-107/mysql/homo_sapiens_core_107_38/
>         md5: ''
>     name: Ensembl
>     website: https://www.ensembl.org/index.html
>     mouse:
>       release-108:
>         source: https://ftp.ensembl.org/pub/release-108/mysql/mus_musculus_core_108_39/
>         md5: ''
> Protein:
>   uniprot:
>     human:
>       2022-04:
>         source: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/
>         md5: ''
>       2022-03:
>         source: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_03/
>         md5: ''
>     name: Uniprot
>     website: https://www.uniprot.org/
>     mouse:
>       2022-04:
>         source: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/
>         md5: ''
> CellMarker:
>   cellmarker:
>     human:
>       '2.0':
>         source: http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx
>         md5: ''
>     name: CellMarker
>     website: http://bio-bigdata.hrbmu.edu.cn/CellMarker/
>     mouse:
>       '2.0':
>         source: http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx
>         md5: ''
> CellLine:
>   clo:
>     all:
>       '2022-03-21':
>         source: https://data.bioontology.org/ontologies/CLO/submissions/65/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ea58a1010b7e745702a8397a526b3a33
>     name: Cell Line Ontology
>     website: https://bioportal.bioontology.org/ontologies/CLO
> CellType:
>   cl:
>     all:
>       '2023-02-15':
>         source: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
>         md5: 9331a6a029cb1863bd0584ab41508df7
>       '2022-08-16':
>         source: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
>         md5: d0655766574e63f3fe5ed56d3c030880
>     name: Cell Ontology
>     website: https://obophenotype.github.io/cell-ontology/
> Tissue:
>   uberon:
>     all:
>       '2023-02-14':
>         source: http://purl.obolibrary.org/obo/uberon/releases/2023-02-14/uberon.owl
>         md5: 3f94e22fae4cdde88a555c5cd59c47da
>       '2022-08-19':
>         source: http://purl.obolibrary.org/obo/uberon/releases/2022-08-19/uberon.owl
>         md5: c7c958a1ee48fdce146f2c1763eed27e
>     name: Uberon multi-species anatomy ontology
>     website: http://obophenotype.github.io/uberon/
> Disease:
>   mondo:
>     all:
>       '2023-02-06':
>         source: http://purl.obolibrary.org/obo/mondo/releases/2023-02-06/mondo.owl
>         md5: 2b7d479d4bd02a94eab47d1c9e64c5db
>       '2022-10-11':
>         source: http://purl.obolibrary.org/obo/mondo/releases/2022-10-11/mondo.owl
>         md5: 04b808d05c2c2e81430b20a0e87552bb
>     name: Mondo Disease Ontology
>     website: https://mondo.monarchinitiative.org/
>   doid:
>     human:
>       '2023-01-30':
>         source: http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo
>         md5: 9f0c92ad2896dda82195e9226a06dc36
>     name: Human Disease Ontology
>     website: https://disease-ontology.org/
> Readout:
>   efo:
>     all:
>       3.48.0:
>         source: http://www.ebi.ac.uk/efo/releases/v3.48.0/efo.owl
>         md5: 3367e9a9ae3dee9113024e5108c49091
>     name: The Experimental Factor Ontology
>     website: https://bioportal.bioontology.org/ontologies/EFO
> Phenotype:
>   hp:
>     human:
>       '2023-01-27':
>         source: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-01-27/hp.owl
>         md5: ceeb3ada771908deef620d74cd8e6b0f
>     name: Human Phenotype Ontology
>     website: https://hpo.jax.org/
> Pathway:
>   go:
>     all:
>       '2023-05-10':
>         source: https://data.bioontology.org/ontologies/GO/submissions/1814/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ''
>     name: Gene Ontology
>     website: http://geneontology.org/docs/download-ontology/
>   pw:
>     all:
>       '7.79':
>         source: https://data.bioontology.org/ontologies/PW/submissions/109/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: 02e2337bb1ab7cc4332ef6acc4cbdfa6
>     name: Pathway Ontology
>     website: https://www.ebi.ac.uk/ols/ontologies/pw
> BFXPipeline:
>   lamin:
>     all:
>       1.0.0:
>         source: s3://bionty-assets/bfxpipelines.json
>         md5: ''
>     name: Bioinformatics Pipeline
>     website: https://lamin.ai
> Drug:
>   dron:
>     all:
>       '2023-03-10':
>         source: https://data.bioontology.org/ontologies/DRON/submissions/17/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ''
>     name: Drug Ontology
>     website: https://bioportal.bioontology.org/ontologies/DRON/?p=summary
>

**Comment by Zethson** [comment]
source.yaml

> version: "0.2.0"
> Species:
>   ensembl:
>     all:
>       release-108:
>         url: https://ftp.ensembl.org/pub/release-108/species_EnsemblVertebrates.txt
>     name: Ensembl
>     website: https://www.ensembl.org/index.html
> Gene:
>   ensembl:
>     human:
>       release-108:
>         url: https://ftp.ensembl.org/pub/release-108/mysql/homo_sapiens_core_108_38/
>       release-107:
>         url: https://ftp.ensembl.org/pub/release-107/mysql/homo_sapiens_core_107_38/
>     mouse:
>       release-108:
>         url: https://ftp.ensembl.org/pub/release-108/mysql/mus_musculus_core_108_39/
>     name: Ensembl
>     website: https://www.ensembl.org/index.html
> Protein:
>   uniprot:
>     human:
>       2022-04:
>         url: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/
>       2022-03:
>         url: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_03/
>     mouse:
>       2022-04:
>         url: https://ftp.uniprot.org/pub/databases/uniprot/previous_releases/release-2022_04/
>     name: Uniprot
>     website: https://www.uniprot.org/
> CellMarker:
>   cellmarker:
>     human:
>       2.0:
>         url: http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx
>     mouse:
>       2.0:
>         url: http://bio-bigdata.hrbmu.edu.cn/CellMarker/CellMarker_download_files/file/Cell_marker_All.xlsx
>     name: CellMarker
>     website: http://bio-bigdata.hrbmu.edu.cn/CellMarker/
> CellLine:
>   clo:
>     all:
>       2022-03-21:
>         url: https://data.bioontology.org/ontologies/CLO/submissions/65/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ea58a1010b7e745702a8397a526b3a33
>     name: Cell Line Ontology
>     website: https://bioportal.bioontology.org/ontologies/CLO
> CellType:
>   cl:
>     all:
>       2023-02-15:
>         url: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
>         md5: 9331a6a029cb1863bd0584ab41508df7
>       2022-08-16:
>         url: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
>         md5: d0655766574e63f3fe5ed56d3c030880
>     name: Cell Ontology
>     website: https://obophenotype.github.io/cell-ontology/
> Tissue:
>   uberon:
>     all:
>       2023-02-14:
>         url: http://purl.obolibrary.org/obo/uberon/releases/2023-02-14/uberon.owl
>         md5: 3f94e22fae4cdde88a555c5cd59c47da
>       2022-08-19:
>         url: http://purl.obolibrary.org/obo/uberon/releases/2022-08-19/uberon.owl
>         md5: c7c958a1ee48fdce146f2c1763eed27e
>     name: Uberon multi-species anatomy ontology
>     website: http://obophenotype.github.io/uberon/
> Disease:
>   mondo:
>     all:
>       2023-02-06:
>         url: http://purl.obolibrary.org/obo/mondo/releases/2023-02-06/mondo.owl
>         md5: 2b7d479d4bd02a94eab47d1c9e64c5db
>       2022-10-11:
>         url: http://purl.obolibrary.org/obo/mondo/releases/2022-10-11/mondo.owl
>         md5: 04b808d05c2c2e81430b20a0e87552bb
>     name: Mondo Disease Ontology
>     website: https://mondo.monarchinitiative.org/
>   doid:
>     human:
>       2023-01-30:
>         url: http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo
>         md5: 9f0c92ad2896dda82195e9226a06dc36
>     name: Human Disease Ontology
>     website: https://disease-ontology.org/
> Readout:
>   efo:
>     all:
>       3.48.0:
>         url: http://www.ebi.ac.uk/efo/releases/v3.48.0/efo.owl
>         md5: 3367e9a9ae3dee9113024e5108c49091
>     name: The Experimental Factor Ontology
>     website: https://bioportal.bioontology.org/ontologies/EFO
> Phenotype:
>   hp:
>     human:
>       2023-01-27:
>         url: https://github.com/obophenotype/human-phenotype-ontology/releases/download/v2023-01-27/hp.owl
>         md5: ceeb3ada771908deef620d74cd8e6b0f
>     name: Human Phenotype Ontology
>     website: https://hpo.jax.org/
> Pathway:
>   go:
>     all:
>       2023-05-10:
>         url: https://data.bioontology.org/ontologies/GO/submissions/1814/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ""
>     name: Gene Ontology
>     website: http://geneontology.org/docs/download-ontology/
>   pw:
>     all:
>       7.79:
>         url: https://data.bioontology.org/ontologies/PW/submissions/109/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: 02e2337bb1ab7cc4332ef6acc4cbdfa6
>     name: Pathway Ontology
>     website: https://www.ebi.ac.uk/ols/ontologies/pw
> BFXPipeline:
>   lamin:
>     all:
>       1.0.0:
>         url: s3://bionty-assets/bfxpipelines.json
>         md5: ""
>     name: Bioinformatics Pipeline
>     website: https://lamin.ai
> Drug:
>   dron:
>     all:
>       2023-03-10:
>         url: https://data.bioontology.org/ontologies/DRON/submissions/17/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb
>         md5: ""
>     name: Drug Ontology
>     website: https://bioportal.bioontology.org/ontologies/DRON/?p=summary
>

**Comment by Zethson** [comment]
Github ate the formatting eww

**Comment by Zethson** [comment]
The burden of being a dev. I had some slightly older format or something.
