### ISSUE TITLE
Fresh Bionty standalone installation misses lamindb_current_source.yaml

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#472]
`FileNotFoundError: [Errno 2] No such file or directory: '/home/zeth/miniconda3/envs/pertpy/lib/python3.10/site-packages/bionty/sources/.lamindb_current_sources.yaml'`

**Comment by sunnyosun** [comment]
You probably have a lamindb instance loaded. It doesn't matter if it's a fresh install because the .env file still exists. You need to run `lamin close`.

**Comment by Zethson** [comment]
Ohhhh, of course....
