### ISSUE TITLE
ICD-10 code list is incomplete

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#550]
Missing terms with `.` and others.

For instance: `I49`, `E78.6` are not on the list, but can be found here: https://www.icd10data.com/ICD10CM/Codes/E00-E89/E70-E88/E78-/E78.6

**Comment by Zethson** [comment]
Added a script that generates a new TSV here: https://github.com/laminlabs/bionty-assets/pull/32

We are waiting for customer feedback on whether we should roll with this or maybe even need a new German term extension. However, we are like 95%+ sure that the new file will be the way to go...
