### ISSUE TITLE
😵 Can we call the same thing the same name?

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#6]
Attribute names from different databases are different...

e.g. 'ensembl_gn_id' in BioMart vs 'ENSEMBL_ID' in Uniprot

→ Write a name normalizer?

**Comment by falexwolf** [comment]
Oh my god! Was this to be expected? Is this something people are aware of? If not, shouldn't be people be educated about this?

**Comment by sunnyosun** [comment]
I think people are aware, just nobody wants to deal with it as usually it's good enough for what they are searching for in a particular case?
