### ISSUE TITLE
Calling `gene.standardize()` takes a _very long_ time 

### ISSUE THREAD

**Issue by falexwolf** [laminlabs/bionty-base#69]
So, maybe this is just the first time calling it. What I did was simply importing bionty and then calling this

<img width="680" alt="image" src="https://user-images.githubusercontent.com/16916678/175379290-a4a27d8e-b338-4e86-95ff-4cacdb322610.png">

And it has been running for 10 min I think... without any logging. 😅 

I'll investigate now.

**Comment by sunnyosun** [comment]
Resolved by moving the tables to the S3.
