### ISSUE TITLE
Allow users to select their gene or protein reference tables, and can provide their own reference as `.df`

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#94]
Currently, only the Ensembl table is allowed and set to the default.

However, in real-world cases, users often use their favorite reference table, e.g. gtf/GFF3 file from [Ensembl](http://asia.ensembl.org/info/data/ftp/index.html/), [Gencode](https://www.gencodegenes.org/human/), or [RefSeq](https://www.ncbi.nlm.nih.gov/genome/guide/human/) for analyzing gene expression datasets.

When users install LaminDB, we'd like them to be able to configure with customized reference tables, meanwhile also offering the above options for them to get started.

**Comment by Zethson** [comment]
@sunnyosun what isn't currently covered here with our version design? Of course we need to add those dataframes as additional ontologies, but generally we're fine, right?
